# Generated by Django 5.2.7 on 2025-10-16 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('domains', '0001_initial'),
        ('prompts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='llmusagelog',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to='prompts.prompttemplate'),
        ),
        migrations.AddField(
            model_name='llmusagelog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='providerratecard',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_cards', to='prompts.modelconfig'),
        ),
        migrations.AddField(
            model_name='llmusagelog',
            name='rate_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_logs', to='billing.providerratecard'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='domains.client'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='domains.client'),
        ),
        migrations.AddField(
            model_name='llmusagelog',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_logs', to='billing.wallet'),
        ),
        migrations.AddField(
            model_name='walletledger',
            name='wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='billing.wallet'),
        ),
        migrations.AlterUniqueTogether(
            name='providerratecard',
            unique_together={('model', 'currency')},
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('client', 'stripe_subscription_id')},
        ),
    ]
