# Generated by Django 5.2.7 on 2025-10-16 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contexts', '0001_initial'),
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='uploads.file'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['file'], name='contexts_do_file_id_1686a5_idx'),
        ),
    ]
