# Generated by Django 5.2.7 on 2025-10-16 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('input_cost_per_1k', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('output_cost_per_1k', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base_url', models.URLField(blank=True)),
                ('api_key_ref', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('body', models.TextField()),
                ('retrieval_k', models.PositiveSmallIntegerField(default=3)),
                ('retrieval_min_score', models.FloatField(default=0.0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='prompts.modelconfig')),
                ('rate_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='billing.providerratecard')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='prompts.provider')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PromptRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rendered_prompt', models.TextField()),
                ('retrieved_context', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usage_log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_run', to='billing.llmusagelog')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='prompts.prompttemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='modelconfig',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='prompts.provider'),
        ),
        migrations.AlterUniqueTogether(
            name='modelconfig',
            unique_together={('provider', 'name')},
        ),
    ]
